name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # recursively checkout all submodules
        submodules: 'recursive'

    - name: install system dependencies
      run: |
        sudo apt update
        sudo apt install -y g++ cmake libboost-all-dev libeigen3-dev libyaml-cpp-dev libfcl-dev libmsgpack-dev libf2c2-dev libglew-dev freeglut3-dev libassimp-dev libqhull-dev libann-dev libglfw3-dev libjsoncpp-dev

    - name: install python dependencies
      run: |
        sudo apt install python3 python3-dev python3-numpy python3-pip
        sudo pip3 install pybind11 pytest cvxpy rowan msgpack tqdm psutil
        sudo pip3 install --upgrade pip
        sudo pip3 install --upgrade "jax[cpu]"

    - name: Configure CMake
      run: |
        mkdir buildRelease
        cd buildRelease
        cmake -DCMAKE_BUILD_TYPE=Release ..
      working-directory: ${{github.workspace}}

    - name: Build
      run: |
        make
      working-directory: ${{github.workspace}}/buildRelease

    - name: Run Tests
      run: |
        pytest ../test
      working-directory: ${{github.workspace}}/buildRelease
